apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: production
  labels:
    app: fastapi-service
data:
  # Application configuration
  APP_NAME: "FastAPI Production Service"
  APP_ENV: "production"
  
  # Logging configuration
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
  
  # Server configuration
  WORKERS: "4"
  WORKER_CLASS: "uvicorn.workers.UvicornWorker"
  WORKER_CONNECTIONS: "1000"
  KEEPALIVE: "5"
  
  # CORS settings
  CORS_ORIGINS: "https://example.com,https://app.example.com"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_PERIOD: "60"
  
  # Monitoring
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"