apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: production
  labels:
    app: fastapi-service
type: Opaque
stringData:
  # Database credentials (example)
  DATABASE_URL: "postgresql://user:password@postgres:5432/dbname"
  
  # API Keys
  API_SECRET_KEY: "your-secret-key-here"
  JWT_SECRET_KEY: "your-jwt-secret-here"
  
  # External service credentials
  REDIS_URL: "redis://:password@redis:6379/0"
  
  # Monitoring credentials
  SENTRY_DSN: "https://key@sentry.io/project"
  
  # Third-party integrations
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
  
# Note: In production, use Sealed Secrets or external secret management
# This is just a template - never commit actual secrets to Git!